# Generated by Django 4.2.16 on 2024-09-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0005_remove_employe_office_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataemploye',
            name='employe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authUser.employe'),
            preserve_default=False,
        ),
    ]
