# Generated by Django 4.2.16 on 2024-09-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0006_dataemploye_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataemploye',
            name='date_resignation',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
