# Generated by Django 4.2.16 on 2024-09-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0007_alter_dataemploye_date_resignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
