# Generated by Django 4.2.16 on 2024-11-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0008_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
