vehicles = [
    {
        "plate": "ABC1234",
        "model": "XF105",
        "n_axes": 2,
        "type_vehicle": "Truck",
        "status": 1,
        "tb_mark": 1,
    },
    {
        "plate": "XYZ5678",
        "model": "Constellation",
        "n_axes": 3,
        "type_vehicle": "Truck",
        "status": 1,
        "tb_mark": 2,
    },
    {
        "plate": "JKL9012",
        "model": "R450",
        "n_axes": 2,
        "type_vehicle": "Truck",
        "status": 2,
        "tb_mark": 3,
    },
    {
        "plate": "MNO3456",
        "model": "Actros",
        "n_axes": 4,
        "type_vehicle": "Truck",
        "status": 1,
        "tb_mark": 4,
    },
    {
        "plate": "PQR7890",
        "model": "Stralis",
        "n_axes": 3,
        "type_vehicle": "Truck",
        "status": 1,
        "tb_mark": 5,
    },
    {
        "plate": "STU1123",
        "model": "Cargo",
        "n_axes": 2,
        "type_vehicle": "Truck",
        "status": 1,
        "tb_mark": 6,
    },
    {
        "plate": "VWX4567",
        "model": "TGS",
        "n_axes": 3,
        "type_vehicle": "Truck",
        "status": 0,
        "tb_mark": 7,
    },
    {
        "plate": "YZA8901",
        "model": "579",
        "n_axes": 2,
        "type_vehicle": "Truck",
        "status": 1,
        "tb_mark": 8,
    },
    {
        "plate": "EFG6789",
        "model": "HD78",
        "n_axes": 2,
        "type_vehicle": "Truck",
        "status": 1,
        "tb_mark": 10,
    },
]
