# Generated by Django 4.2.16 on 2024-10-08 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authUser', '0008_user_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_position', models.CharField(max_length=50)),
                ('date_preview_delivery', models.DateTimeField()),
                ('date_effected_delivery', models.DateTimeField(blank=True, null=True)),
                ('date_preview_colect', models.DateTimeField()),
                ('date_effected_colect', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payer_identification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('payer_identification_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7)),
                ('model', models.CharField(max_length=50)),
                ('n_axes', models.IntegerField()),
                ('type_vehicle', models.CharField(max_length=45)),
                ('status', models.IntegerField(choices=[(1, 'Running'), (2, 'Maintenance'), (3, 'Stopped'), (4, 'Broken')], default=3)),
                ('tb_mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='carrier.mark')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'aguardando pagameto'), (1, 'pagamento aprovado'), (2, 'em preparação'), (3, 'aguardando coleta'), (4, 'em andamento'), (5, 'padido coletado'), (6, 'Pronto para a entrega'), (7, 'aguardando entrega'), (8, 'entregue'), (9, 'Falha na entrega'), (10, 'Devolvido'), (11, 'Cancelado')], default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authUser.client')),
                ('id_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrier.delivery')),
                ('id_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authUser.driver')),
                ('id_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrier.payment')),
                ('id_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='carrier.vehicle')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('observation', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrier.order')),
            ],
            options={
                'verbose_name': 'Item Order',
                'verbose_name_plural': 'Items Orders',
            },
        ),
    ]
