# Generated by Django 4.2.16 on 2024-09-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7)),
                ('model', models.CharField(max_length=50)),
                ('n_axes', models.IntegerField()),
                ('type_vehicle', models.CharField(max_length=45)),
                ('status', models.IntegerField(choices=[(1, 'Running'), (2, 'Maintenance'), (3, 'Stopped'), (4, 'Broken')], default=3)),
                ('tb_mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='carrier.mark')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
