# Generated by Django 4.2.16 on 2024-09-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_payment_alter_vehicle_tb_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_position', models.CharField(max_length=50)),
                ('date_preview_delivery', models.DateTimeField()),
                ('date_effected_delivery', models.DateTimeField()),
                ('date_preview_colect', models.DateTimeField()),
                ('date_effected_colect', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
