# Generated by Django 4.2.16 on 2024-09-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0003_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date_effected_colect',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date_effected_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
