# Generated by Django 4.2.16 on 2024-09-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0008_user_telephone'),
        ('carrier', '0004_alter_delivery_date_effected_colect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'aguardando pagameto'), (1, 'pagamento aprovado'), (2, 'em preparação'), (3, 'aguardando coleta'), (4, 'em andamento'), (5, 'padido coletado'), (6, 'Pronto para a entrega'), (7, 'aguardando entrega'), (8, 'entregue'), (9, 'Falha na entrega'), (10, 'Devolvido'), (11, 'Cancelado')], default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authUser.client')),
                ('id_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrier.delivery')),
                ('id_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authUser.driver')),
                ('id_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrier.payment')),
                ('id_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='carrier.vehicle')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
