# Generated by Django 4.2.16 on 2024-10-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('observation', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carrier.order')),
            ],
            options={
                'verbose_name': 'Item Order',
                'verbose_name_plural': 'Items Orders',
            },
        ),
    ]
