# Generated by Django 4.2.16 on 2024-10-07 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0006_itemorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aguardando Pagameto'), (1, 'Pagamento Aprovado'), (2, 'Em Preparação'), (3, 'Aguardando Coleta'), (4, 'Em Andamento'), (5, 'Pedido Coletado'), (6, 'Pronto Para a Entrega'), (7, 'Aguardando Entrega'), (8, 'Entregue'), (9, 'Falha na Entrega'), (10, 'Devolvido'), (11, 'Cancelado')], default=0),
        ),
        migrations.CreateModel(
            name='AddressOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('typeAddress', models.CharField(choices=[('DE', 'Delivery'), ('CO', 'Collect')], default='DE', max_length=2)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='carrier.order')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
