# Generated by Django 4.2.16 on 2024-10-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0007_alter_order_status_addressorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressorder',
            name='typeAddress',
            field=models.CharField(choices=[('0', 'DELIVERY'), ('1', 'COLLECT')], default='0', max_length=2),
        ),
    ]
