# Generated by Django 4.2.16 on 2024-10-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0008_alter_addressorder_typeaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressorder',
            old_name='order_id',
            new_name='id_order',
        ),
    ]
