# Generated by Django 4.2.16 on 2024-10-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0009_rename_order_id_addressorder_id_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='value',
            new_name='transaction_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date_generated',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_email',
            field=models.EmailField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_identification_number',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_identification_type',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='00', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
