# Generated by Django 4.2.16 on 2024-10-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0010_rename_value_payment_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pix_copyPaste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
