# Generated by Django 4.2.16 on 2024-10-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0012_rename_payment_method_payment_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_generated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_update',
            field=models.DateTimeField(null=True),
        ),
    ]
