# Generated by Django 4.2.16 on 2024-10-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0013_payment_date_generated_payment_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ticket_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
