# Generated by Django 4.2.16 on 2024-10-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0014_payment_ticket_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
