# Generated by Django 4.2.16 on 2024-10-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0016_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='installments',
        ),
        migrations.AddField(
            model_name='payment',
            name='installments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
