# Generated by Django 4.2.16 on 2024-10-20 18:56

import core.carrier.models.card
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0017_remove_card_installments_payment_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.CharField(max_length=5, validators=[core.carrier.models.card.validate_expiration_date]),
        ),
    ]
