# Generated by Django 4.2.16 on 2024-10-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0019_payment_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
