# Generated by Django 4.2.16 on 2024-11-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0020_alter_card_options_alter_payment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='driver_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
