# Generated by Django 4.2.16 on 2024-12-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0021_alter_delivery_driver_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pix_copyPaste',
            field=models.TextField(blank=True, null=True),
        ),
    ]
