# Generated by Django 4.2.16 on 2024-12-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0022_alter_payment_pix_copypaste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='driver_position',
            field=models.TextField(blank=True, null=True),
        ),
    ]
