# Generated by Django 4.2.16 on 2024-12-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0023_alter_delivery_driver_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
