# Generated by Django 4.2.16 on 2024-12-12 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0024_delivery_address_delivery_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressorder',
            name='id_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.order'),
        ),
    ]
