# Generated by Django 4.2.16 on 2024-12-12 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0025_alter_addressorder_id_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='id_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.order'),
        ),
    ]
